---
deprecations:
  - |
    The ``hide_server_address_states`` configuration option is now
    deprecated for removal. In future, there will be hard coded
    server state ``building`` for which server address will be hidden.
    The policy 'os_compute_api:os-hide-server-addresses' also is deprecated
    for removal. More details `here`_

    .. _here: https://specs.openstack.org/openstack/nova-specs/specs/queens/approved/remove-configurable-hide-server-address-feature.html
