# See https://docs.openstack.org/infra/manual/drivers.html#naming-with-zuul-v3
# for job naming conventions.
- job:
    name: nova-dsvm-base
    parent: legacy-dsvm-base
    description: |
      The base job definition for nova devstack/tempest jobs.
      Contains common configuration.
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/nova
      - openstack/tempest
    irrelevant-files: &dsvm-irrelevant-files
      - ^(placement-)?api-.*$
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^.git.*$
      - ^doc/.*$
      - ^nova/hacking/.*$
      - ^nova/locale/.*$
      - ^nova/tests/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tests-py3.txt$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: nova-dsvm-multinode-base
    parent: legacy-dsvm-base-multinode
    description: |
      Base job for multinode nova devstack/tempest jobs.
      Will setup firewall rules on all the nodes allowing them to talk to
      each other.
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/nova
      - openstack/tempest
    irrelevant-files: *dsvm-irrelevant-files
    nodeset: legacy-ubuntu-xenial-2-node

- job:
    name: nova-tox-functional
    parent: openstack-tox
    description: |
      Run tox-based functional tests for the OpenStack Nova project with Nova
      specific irrelevant-files list. Uses tox with the ``functional``
      environment.
    irrelevant-files: &functional-irrelevant-files
      - ^.*\.rst$
      - ^api-.*$
      - ^doc/source/.*$
      - ^nova/locale/.*$
      - ^placement-api-ref/.*$
      - ^releasenotes/.*$
    vars:
      tox_envlist: functional
    timeout: 3600

- job:
    name: nova-tox-functional-py35
    parent: openstack-tox
    description: |
      Run tox-based functional tests for the OpenStack Nova project
      under cPython version 3.5. with Nova specific irrelevant-files list.
      Uses tox with the ``functional-py35`` environment.
    irrelevant-files: *functional-irrelevant-files
    vars:
      tox_envlist: functional-py35
    timeout: 3600

- job:
    name: nova-caching-scheduler
    parent: nova-dsvm-base
    description: |
      Run non-slow Tempest API and scenario tests using the CachingScheduler.
    run: playbooks/legacy/nova-caching-scheduler/run.yaml
    post-run: playbooks/legacy/nova-caching-scheduler/post.yaml

- job:
    name: nova-cells-v1
    parent: nova-dsvm-base
    run: playbooks/legacy/nova-cells-v1/run.yaml
    post-run: playbooks/legacy/nova-cells-v1/post.yaml

- job:
    name: nova-live-migration
    parent: nova-dsvm-multinode-base
    run: playbooks/legacy/nova-live-migration/run.yaml
    post-run: playbooks/legacy/nova-live-migration/post.yaml
    irrelevant-files:
      - ^(placement-)?api-.*$
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^.git.*$
      - ^doc/.*$
      - ^nova/hacking/.*$
      - ^nova/locale/.*$
      - ^nova/tests/unit/.*$
      - ^nova/tests/functional/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tests-py3.txt$
      - ^tools/.*$
      - ^tox.ini$

- job:
    name: nova-lvm
    parent: nova-dsvm-base
    description: |
      Run tempest compute API tests using LVM image backend. This only runs
      against nova/virt/libvirt/* changes.
    run: playbooks/legacy/nova-lvm/run.yaml
    post-run: playbooks/legacy/nova-lvm/post.yaml
    # Copy irrelevant-files from nova-dsvm-base and then exclude anything
    # that is not in the nova/virt/libvirt/* tree (besides the actual zuul
    # playbook and tempest rc files so this can be self-testing).
    irrelevant-files:
      - ^(?!.zuul.yaml)(?!playbooks/legacy/nova-lvm/)(?!devstack/tempest-dsvm-lvm-rc)(?!nova/virt/libvirt/).*$
      - ^(placement-)?api-.*$
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^.git.*$
      - ^doc/.*$
      - ^nova/hacking/.*$
      - ^nova/locale/.*$
      - ^nova/tests/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tests-py3.txt$
      - ^tools/.*$
      - ^tox.ini$
    # TODO(mriedem): Make this voting and gating once bug 1771700 is fixed
    # and we've had enough runs to feel comfortable with this setup.
    voting: false

- job:
    name: nova-multiattach
    parent: nova-dsvm-base
    description: |
      Run tempest integration tests with volume multiattach support enabled.
      This job will only work starting with Queens.
      It uses the default Cinder volume type in devstack (lvm) and the
      default compute driver in devstack (libvirt).
    run: playbooks/legacy/nova-multiattach/run.yaml
    post-run: playbooks/legacy/nova-multiattach/post.yaml

- job:
    name: nova-next
    parent: nova-dsvm-base
    description: |
      This job was added in Newton when placement and cellsv2
      were optional. Placement and cellsv2 are required starting in Ocata. In
      Pike, the service user token functionality was added. This job is also
      unique in that it runs the post_test_hook from the nova repo, which runs
      post-test scripts to ensure those scripts are still working,
      e.g. archive_deleted_rows. In Queens, this job started testing the
      TLS console proxy code in the libvirt driver.
    run: playbooks/legacy/nova-next/run.yaml
    post-run: playbooks/legacy/nova-next/post.yaml

- job:
    name: tempest-nova-v2-api
    parent: devstack-tempest
    branches:
      - master
    description: |
      This job runs the Tempest compute tests against v2.0 endpoint.
      Former names for this job was:
        * legacy-tempest-dsvm-nova-v20-api
    vars:
      tox_envlist: all
      tempest_test_regex: api.*compute
      devstack_localrc:
        TEMPEST_COMPUTE_TYPE: compute_legacy

- job:
    name: nova-grenade-live-migration
    parent: nova-dsvm-multinode-base
    description: |
      Multi-node grenade job which runs nova/tests/live_migration/hooks tests.
      In other words, this tests live migration with mixed-version compute
      services which is important for things like rolling upgrade support.
      The former name for this job was
      "legacy-grenade-dsvm-neutron-multinode-live-migration".
    run: playbooks/legacy/nova-grenade-live-migration/run.yaml
    post-run: playbooks/legacy/nova-grenade-live-migration/post.yaml
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/nova
    irrelevant-files:
      - ^(placement-)?api-.*$
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^.git.*$
      - ^api-.*$
      - ^doc/.*$
      - ^nova/hacking/.*$
      - ^nova/locale/.*$
      - ^nova/tests/.*\.py$
      - ^nova/tests/functional/.*$
      - ^nova/tests/unit/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tests-py3.txt$
      - ^tools/.*$
      - ^tox.ini$
    voting: false

- project:
    # Please try to keep the list of job names sorted alphabetically.
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - periodic-stable-jobs
      - check-requirements
      - integrated-gate
      - integrated-gate-py35
      - release-notes-jobs
    check:
      jobs:
        # We define our own irrelevant-files so we don't run the job
        # on things like nova docs-only changes.
        - ironic-tempest-dsvm-ipa-wholedisk-bios-agent_ipmitool-tinyipa:
            voting: false
            irrelevant-files: *dsvm-irrelevant-files
        - nova-cells-v1
        - nova-grenade-live-migration
        - nova-live-migration
        - nova-lvm
        - nova-multiattach
        - nova-next
        - tempest-slow:
            irrelevant-files: *dsvm-irrelevant-files
        - nova-tox-functional
        - nova-tox-functional-py35
        - openstack-tox-lower-constraints:
            # NOTE(elod.illes): with the introduction of the new dependency
            # resolver in pip 20.3, the lower-constraints jobs start to fail
            # as the constraint handling is now working as it should, thus
            # revealing issues. Setting this to non-voting until the way
            # forward is decided.
            voting: false
        - tempest-full-py3:
            irrelevant-files: *dsvm-irrelevant-files
        - neutron-grenade-multinode:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - devstack-plugin-ceph-tempest:
            voting: false
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - neutron-tempest-linuxbridge:
            irrelevant-files:
              - ^(?!nova/network/.*)(?!nova/virt/libvirt/vif.py).*$
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - tempest-multinode-full:
            voting: false
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - tempest-full:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - neutron-grenade:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
    gate:
      jobs:
        - nova-cells-v1
        - nova-live-migration
        - nova-multiattach
        - nova-next
        - tempest-slow:
            irrelevant-files: *dsvm-irrelevant-files
        - nova-tox-functional
        - nova-tox-functional-py35
        - openstack-tox-lower-constraints:
            # NOTE(elod.illes): with the introduction of the new dependency
            # resolver in pip 20.3, the lower-constraints jobs start to fail
            # as the constraint handling is now working as it should, thus
            # revealing issues. Setting this to non-voting until the way
            # forward is decided.
            voting: false
        - tempest-full-py3:
            irrelevant-files: *dsvm-irrelevant-files
        - tempest-full:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - neutron-grenade:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
    experimental:
      jobs:
        - nova-caching-scheduler
        - os-vif-ovs
        - tempest-nova-v2-api:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-tempest-dsvm-multinode-full:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - neutron-tempest-dvr-ha-multinode-full:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-tempest-dsvm-neutron-src-oslo.versionedobjects:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-tempest-dsvm-nova-libvirt-kvm-apr:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-grenade-dsvm-neutron-multinode-zero-downtime:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - ironic-tempest-dsvm-ipa-wholedisk-agent_ipmitool-tinyipa-multinode:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^.git.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^tests-py3.txt$
        - ironic-tempest-dsvm-bfv:
            # NOTE: Ironic boot from volume only works starting in stable/pike.
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^.git.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^tests-py3.txt$
        - devstack-plugin-nfs-tempest-full:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-barbican-simple-crypto-dsvm-tempest-nova
        - devstack-plugin-ceph-tempest-py3:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
        - legacy-tempest-dsvm-neutron-pg-full:
            irrelevant-files:
              - ^(placement-)?api-.*$
              - ^(test-|)requirements.txt$
              - ^.*\.rst$
              - ^.git.*$
              - ^doc/.*$
              - ^nova/hacking/.*$
              - ^nova/locale/.*$
              - ^nova/tests/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^tests-py3.txt$
              - ^tools/.*$
              - ^tox.ini$
    post:
      jobs:
        - openstack-tox-cover
