- hosts: all
  name: nova-next
  tasks:

    - name: Ensure workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        # TODO(mriedem): Consider setting USE_PYTHON3=True here to make this
        # job run under python 3.5 which is a "next" type thing.

        # Enable TLS between the noVNC proxy & compute nodes; this requires
        # the tls-proxy service to be enabled.
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          NOVA_USE_SERVICE_TOKEN=True
          NOVA_CONSOLE_PROXY_COMPUTE_TLS=True
          PLACEMENT_DB_ENABLED=True

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          # tls-proxy is needed to initialize the CA and cert.
          export ENABLED_SERVICES=tls-proxy
          export PYTHONUNBUFFERED=true
          # Yes we want to run Tempest.
          export DEVSTACK_GATE_TEMPEST=1
          # Run non-slow tempest API tests (concurrently) and scenario
          # tests (serially).
          export DEVSTACK_GATE_TEMPEST_FULL=1
          # The post_test_hook runs some post-test CLIs for things that
          # Tempest does not test, like archiving deleted records.
          function post_test_hook {
              if [ -f $BASE/new/nova/gate/post_test_hook.sh ]; then
                  $BASE/new/nova/gate/post_test_hook.sh
              fi
          }
          export -f post_test_hook
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
